version: "3"
services:
    db:
        image: mysql:8.0
        restart: always
        ports:
            - 3306:3306
        container_name: mysqldb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=ecommerceapp
            - MYSQL_PASSWORD=ecommerceapp
            - MYSQL_DATABASE=full-stack-ecommerce
        volumes:
            - ./mysql:/var/lib/mysql # persistent database data.
            - ./db-scripts:/docker-entrypoint-initdb.d #scripts